name = "tinyauth-backgrounds"
main = "src/index.js"
compatibility_date = "2025-08-15"

# R2 bucket binding for storing image data
[[r2_buckets]]
binding = "UNSPLASH_CACHE"
bucket_name = "unsplash-cache"

# KV namespace binding for storing cache metadata
[[kv_namespaces]]
binding = "UNSPLASH_CACHE_METADATA"
id = "86c621d1e7e445df99cae2dfe161d777"  # Replace with actual namespace ID after creation

# Cron trigger for automatic cache cleanup
# Runs daily at 2:00 AM UTC
[triggers]
crons = ["0 2 * * *"]

[observability.logs]
enabled = true